delhiMetro = {
    # "Station name": ["the stations it is directly connected to"]

    # Green Line
    'City Park':['Bus Stand'],
    'Bus Stand':['City Park','Modern Industrial Estate'],
    'Modern Industrial Estate':['Bust Stand','Tikri Border'],
    'Tikri Border':['Tikri Kalan','Modern Industrial Estate'],
    'Tikri Kalan':['Tikri Border','Ghevra Metro Station'],
    'Ghevra Metro Station':['Tikri Kalan','Mundka Industrial Area'],
    'Mundka Industrial Area':['Mundka','Ghevra Metro Sation']
}

def indexOf(list,ele):
    try:
        return list.index(ele)
    except:
        return -1

# To be checked
delhiMetro1 = {
    'Dilshad Garden':['Jhilmil'],
    'Jhilmil':['Dilshad Garden','Mansrovar park'],
    'Mansrovar park':['Jhilmil','Shahdara'],
    'Shahdara':['Mansrovar park','Welcome'],
    'Welcome':['Shahdara','Seelampur'],
    'Seelampur':['Welcome','Shastri Park'],
    'Shastri Park':['Seelampur','Kashmere Gate'],
    'Kashmere Gate':['Shastri Park','Tis Hazari'],
    'Tis Hazari':['Kashmere Gate','Pul Bangash'],
    'Pul Bangash':['Tis Hazari','Pratap Nagar'],
    'Pratap Nagar':['Pul Bangash','Shastri Nagar'],
    'Shastri Nagar':['Pratap Nagar','Inder Lok'],
    'Inder Lok':['Shastri Nagar','Kanhaiya Nagar'],
    'Kanhaiya Nagar':['Inder Lok','Keshav Puram'],
    'Keshav Puram':['Kanhaiya Nagar','Netaji Subash Place'],
    'Netaji Subash Place':['Keshav Puram','Kohat Enclave'],
    'Kohat Enclave':['Netaji Subash Place','Pitam Pura'],
    'Pitam Pura':['Kohat Enclave','Rohini East'],
    'Rohini East':['Pitam Pura','Rohini West'],
    'Rohini West':['Rohini East','Rithala'],
    'Rithala':['Rohini West','Samaypur Badli'],
    'Samaypur Badli':['Rithala','Rohini Sector - 18'],
    'Rohini Sector - 18':['Samaypur Badli','Haiderpur Badli Mor'],
    'Haiderpur Badli Mor':['Rohini Sector - 18','Jahangirpuri'],
    'Jahangirpuri':['Haiderpur Badli Mor','Adarsh Nagar'],
    'Adarsh Nagar':['Jahangirpuri','Azadpur'],
    'Azadpur':['Adarsh Nagar','Model Town'],
    'Model Town':['Azadpur','GTB Nagar'],
    'GTB Nagar':['Model Town','Vishwavidyalaya'],
    'Vishwavidyalaya':['GTB Nagar','Vidhan Sabha'],
    'Vidhan Sabha':['Vishwavidyalaya','Civil Lines'],
    'Civil Lines':['Vidhan Sabha','Kashmere Gate'],
    'Kashmere Gate':['Civil Lines','Chandhni Chowk'],
    'Chandhni Chowk':['Kashmere Gate','Chawri Bazar'],
    'Chawri Bazar':['Chandhni Chowk','New Delhi'],
    'New Delhi':['Chawri Bazar','Rajiv Chowk'],
    'Rajiv Chowk':['New Delhi','Patel Chowk'],
    'Patel Chowk':['Rajiv Chowk','Central Secretariat'],
    'Central Secretariat':['Patel Chowk','Udyog Bhawan'],
    'Udyog Bhawan':['Central Secretariat','Lok Kalyan Marg'],
    'Lok Kalyan Marg':['Udyog Bhawan','Jorbagh'],
    'Jorbagh':['Lok Kalyan Marg','INA'],
    'INA':['Jorbagh','AIIMS'],
    'AIIMS':['INA','Green Park'],
    'Green Park':['AIIMS','Hauz Khas'],
    'Hauz Khas':['Green Park','Malviya Nagar'],
    'Malviya Nagar':['Hauz Khas','Saket'],
    'Saket':['Malviya Nagar','Qutab Minar'],
    'Qutab Minar':['Saket','Chhattarpur'],
    'Chhattarpur':['Qutab Minar','Sultanpur'],
    'Sultanpur':['Chhattarpur','Ghitorni'],
    'Ghitorni':['Sultanpur','Arjan Garh'],
    'Arjan Garh':['Ghitorni','Guru Dronacharya'],
    'Guru Dronacharya':['Arjan Garh','Sikandarpur'],
    'Sikandarpur':['Guru Dronacharya','MG Road'],
    'MG Road':['Sikandarpur','IFFCO Chowk'],
    'IFFCO Chowk':['MG Road','Huda City Centre'],
    'Huda City Centre':['IFFCO Chowk','Noida City Centre'],
    'Noida City Centre':['Huda City Centre','Golf Course'],
    'Golf Course':['Noida City Centre','Botanical Garden'],
    'Botanical Garden':['Golf Course','Noida Sect 18'],
    'Noida Sect 18':['Botanical Garden','Noida Sect 16'],
    'Noida Sect 16':['Noida Sect 18','Noida Sect 15'],
    'Noida Sect 15':['Noida Sect 16','New Ashok Nagar'],
    'New Ashok Nagar':['Noida Sect 15','Mayur Vihar Ext'],
    'Mayur Vihar Ext':['New Ashok Nagar','Mayur Vihar-I'],
    'Mayur Vihar-I':['Mayur Vihar Ext','Akshardham'],
    'Akshardham':['Mayur Vihar-I','Yamuna Bank'],
    'Yamuna Bank':['Akshardham','Indraprastha'],
    'Indraprastha':['Yamuna Bank','Pragati Maidan'],
    'Pragati Maidan':['Indraprastha','Mandi House'],
    'Mandi House':['Pragati Maidan','Barakhamba Road'],
    'Barakhamba Road':['Mandi House','Rajiv Chowk'],
    'Rajiv Chowk':['Barakhamba Road','RK Ashram Marg'],
    'RK Ashram Marg':['Rajiv Chowk','Jhandewalan'],
    'Jhandewalan':['RK Ashram Marg','Karol Bagh'],
    'Karol Bagh':['Jhandewalan','Rajendra Place'],
    'Rajendra Place':['Karol Bagh','Patel Nagar'],
    'Patel Nagar':['Rajendra Place','Shadipur'],
    'Shadipur':['Patel Nagar','Kirti Nagar'],
    'Kirti Nagar':['Shadipur','Moti Nagar'],
    'Moti Nagar':['Kirti Nagar','Ramesh Nagar'],
    'Ramesh Nagar':['Moti Nagar','Rajouri Garden'],
    'Rajouri Garden':['Ramesh Nagar','Tagore Garden'],
    'Tagore Garden':['Rajouri Garden','Subash Nagar'],
    'Subash Nagar':['Tagore Garden','Tilak Nagar'],
    'Tilak Nagar':['Subash Nagar','Janak Puri East'],
    'Janak Puri East':['Tilak Nagar','Janak Puri West'],
    'Janak Puri West':['Janak Puri East','Uttam Nagar East'],
    'Uttam Nagar East':['Janak Puri West','Uttam Nagar West'],
    'Uttam Nagar West':['Uttam Nagar East','Nawada'],
    'Nawada':['Uttam Nagar West','Dwarka Mor'],
    'Dwarka Mor':['Nawada','Dwarka'],
    'Dwarka':['Dwarka Mor','Dwarka Sector - 14'],
    'Dwarka Sector - 14':['Dwarka','Dwarka Sector - 13'],
    'Dwarka Sector - 13':['Dwarka Sector - 14','Dwarka Sector - 12'],
    'Dwarka Sector - 12':['Dwarka Sector - 13','Dwarka Sector - 11'],
    'Dwarka Sector - 11':['Dwarka Sector - 12','Dwarka Sector - 10'],
    'Dwarka Sector - 10':['Dwarka Sector - 11','Dwarka Sector - 9'],
    'Dwarka Sector - 9':['Dwarka Sector - 10','Dwarka Sector - 8'],
    'Dwarka Sector - 8':['Dwarka Sector - 9','Dwarka Sector - 21'],
    'Dwarka Sector - 21':['Dwarka Sector - 8','Vaishali'],
    'Vaishali':['Dwarka Sector - 21','Kaushambi'],
    'Kaushambi':['Vaishali','Anand Vihar'],
    'Anand Vihar':['Kaushambi','Karkar Duma'],
    'Karkar Duma':['Anand Vihar','Preet Vihar'],
    'Preet Vihar':['Karkar Duma','Nirman Vihar'],
    'Nirman Vihar':['Preet Vihar','Laxmi Nagar'],
    'Laxmi Nagar':['Nirman Vihar','Yamuna Bank'],
    'City Park':['Bus Stand'],
    'Bus Stand':['City Park','Modern Industrial Estate'],
    'Modern Industrial Estate':['Bus Stand','Tikri Border'],
    'Tikri Border':['Modern Industrial Estate','Tikri Kalan'],
    'Tikri Kalan':['Tikri Border','Ghevra Metro Station'],
    'Ghevra Metro Station':['Tikri Kalan','Mundka Industrial Area'],
    'Mundka Industrial Area':['Ghevra Metro Station','Mundka'],
    'Mundka':['Mundka Industrial Area','Rajdhani Park'],
    'Rajdhani Park':['Mundka','Nangloi Rly. Station'],
    'Nangloi Rly. Station':['Rajdhani Park','Nangloi'],
    'Nangloi':['Nangloi Rly. Station','Surajmal Stadium'],
    'Surajmal Stadium':['Nangloi','Udyog Nagar'],
    'Udyog Nagar':['Surajmal Stadium','Peera Garhi'],
    'Peera Garhi':['Udyog Nagar','Paschim Vihar (West)'],
    'Paschim Vihar (West)':['Peera Garhi','Paschim Vihar (East)'],
    'Paschim Vihar (East)':['Paschim Vihar (West)','Madi Pur'],
    'Madi Pur':['Paschim Vihar (East)','Shivaji Park'],
    'Shivaji Park':['Madi Pur','Punjabi Bagh'],
    'Punjabi Bagh':['Shivaji Park','Ashok Park Main'],
    'Ashok Park Main':['Punjabi Bagh','Inder Lok'],
    'Inder Lok':['Ashok Park Main','Satguru Ram Singh Marg'],
    'Satguru Ram Singh Marg':['Inder Lok','Kirti Nagar'],
    'Kirti Nagar':['Satguru Ram Singh Marg','Kashmere Gate'],
    'Kashmere Gate':['Kirti Nagar','Lal Quila'],
    'Lal Quila':['Kashmere Gate','Jama Masjid'],
    'Jama Masjid':['Lal Quila','Delhi Gate'],
    'Delhi Gate':['Jama Masjid','ITO'],
    'ITO':['Delhi Gate','Mandi House'],
    'Mandi House':['ITO','Janpath'],
    'Janpath':['Mandi House','Central Secretariat'],
    'Central Secretariat':['Janpath','Khan Market'],
    'Khan Market':['Central Secretariat','JLN'],
    'JLN':['Khan Market','Jangpura'],
    'Jangpura':['JLN','Lajpat Nagar'],
    'Lajpat Nagar':['Jangpura','Moolchand'],
    'Moolchand':['Lajpat Nagar','Kailash Colony'],
    'Kailash Colony':['Moolchand','Nehru Place'],
    'Nehru Place':['Kailash Colony','Kalkaji Mandir'],
    'Kalkaji Mandir':['Nehru Place','Govindpuri'],
    'Govindpuri':['Kalkaji Mandir','Okhla'],
    'Okhla':['Govindpuri','Jasola-Apollo'],
    'Jasola-Apollo':['Okhla','Sarita Vihar'],
    'Sarita Vihar':['Jasola-Apollo','Mohan Estate'],
    'Mohan Estate':['Sarita Vihar','Tuglakabad'],
    'Tuglakabad':['Mohan Estate','Badarpur'],
    'Badarpur':['Tuglakabad','Sarai'],
    'Sarai':['Badarpur','NHPC Chowk'],
    'NHPC Chowk':['Sarai','Mewala Maharajpur'],
    'Mewala Maharajpur':['NHPC Chowk','Sector-28'],
    'Sector-28':['Mewala Maharajpur','Badkal Mor'],
    'Badkal Mor':['Sector-28','Old Faridabad'],
    'Old Faridabad':['Badkal Mor','Neelam Chowk Ajronda'],
    'Neelam Chowk Ajronda':['Old Faridabad','Bata Chowk'],
    'Bata Chowk':['Neelam Chowk Ajronda','Escorts Mujesar'],
    'Escorts Mujesar':['Bata Chowk','Sant Surdas'],
    'Sant Surdas':['Escorts Mujesar','Raja Nahar Singh'],
    'Raja Nahar Singh':['Sant Surdas','Botanical Garden'],
    'Botanical Garden':['Raja Nahar Singh','Okhla Bird Sanctuary'],
    'Okhla Bird Sanctuary':['Botanical Garden','Kalindi Kunj'],
    'Kalindi Kunj':['Okhla Bird Sanctuary','Jasola Vihar'],
    'Jasola Vihar':['Kalindi Kunj','Okhla Vihar'],
    'Okhla Vihar':['Jasola Vihar','Jamia Milia Islamiya'],
    'Jamia Milia Islamiya':['Okhla Vihar','Sukhdev Vihar'],
    'Sukhdev Vihar':['Jamia Milia Islamiya','NSIC Okhla'],
    'NSIC Okhla':['Sukhdev Vihar','Kalkaji Mandir'],
    'Kalkaji Mandir':['NSIC Okhla','Nehru Enclave'],
    'Nehru Enclave':['Kalkaji Mandir','Greater Kailash'],
    'Greater Kailash':['Nehru Enclave','Chirag Delhi'],
    'Chirag Delhi':['Greater Kailash','Panchsheel Park'],
    'Panchsheel Park':['Chirag Delhi','Hauz Khas'],
    'Hauz Khas':['Panchsheel Park','I.I.T'],
    'I.I.T':['Hauz Khas','R.K.Puram'],
    'R.K.Puram':['I.I.T','Munirka'],
    'Munirka':['R.K.Puram','Vasant Vihar'],
    'Vasant Vihar':['Munirka','Shankar Vihar'],
    'Shankar Vihar':['Vasant Vihar','IGD Airport'],
    'IGD Airport':['Shankar Vihar','Sadar Bazar'],
    'Sadar Bazar':['IGD Airport','Palam'],
    'Palam':['Sadar Bazar','Dashrathpuri'],
    'Dashrathpuri':['Palam','Dabri Mor'],
    'Dabri Mor':['Dashrathpuri','Janak Puri West'],
    'Janak Puri West':['Dabri Mor','Majlis Park'],
    'Majlis Park':['Janak Puri West','Azadpur'],
    'Azadpur':['Majlis Park','Shalimar Bagh'],
    'Shalimar Bagh':['Azadpur','Netaji Subash Place'],
    'Netaji Subash Place':['Shalimar Bagh','Shakurpur'],
    'Shakurpur':['Netaji Subash Place','Punjabi Bagh West'],
    'Punjabi Bagh West':['Shakurpur','ESI Hospital'],
    'ESI Hospital':['Punjabi Bagh West','Rajouri Garden'],
    'Rajouri Garden':['ESI Hospital','Mayapuri'],
    'Mayapuri':['Rajouri Garden','Naraina Vihar'],
    'Naraina Vihar':['Mayapuri','Delhi Cantt.'],
    'Delhi Cantt.':['Naraina Vihar','Durgabai Deshmukh South Campus'],
    'Durgabai Deshmukh South Campus':['Delhi Cantt.','Sir Vishweshwaraiah Moti Bagh'],
    'Sir Vishweshwaraiah Moti Bagh':['Durgabai Deshmukh South Campus','Bhikaji Cama Place'],
    'Bhikaji Cama Place':['Sir Vishweshwaraiah Moti Bagh','Sarojini Nagar'],
    'Sarojini Nagar':['Bhikaji Cama Place','INA'],
    'INA':['Sarojini Nagar','South Extension'],
    'South Extension':['INA','Lajpat Nagar'],
    'Lajpat Nagar':['South Extension','Trilokpuri'],
    'Trilokpuri':['Lajpat Nagar','Vinod Nagar East'],
    'Vinod Nagar East':['Trilokpuri','Vinod Nagar'],
    'Vinod Nagar':['Vinod Nagar East','I.P. Extension'],
    'I.P. Extension':['Vinod Nagar','Anand Vihar'],
    'Anand Vihar':['I.P. Extension','Karkar Duma'],
    'Karkar Duma':['Anand Vihar','Karkarduma Court'],
    'Karkarduma Court':['Karkar Duma','Krishna Nagar'],
    'Krishna Nagar':['Karkarduma Court','East Azad Nagar'],
    'East Azad Nagar':['Krishna Nagar','Welcome'],
    'Welcome':['East Azad Nagar','Jafrabad'],
    'Jafrabad':['Welcome','Maujpur'],
    'Maujpur':['Jafrabad','Gokulpuri'],
    'Gokulpuri':['Maujpur','Johri Enclave'],
    'Johri Enclave':['Gokulpuri','Shiv Vihar'],
    'Shiv Vihar':['Johri Enclave','Sector 55-56'],
    'Sector 55-56':['Shiv Vihar','Sector 54 Chowk'],
    'Sector 54 Chowk':['Sector 55-56','Sector 53-54'],
    'Sector 53-54':['Sector 54 Chowk','Sector 42-43'],
    'Sector 42-43':['Sector 53-54','Phase-I'],
    'Phase-I':['Sector 42-43','Sikanderpur'],
    'Sikanderpur':['Phase-I','Phase 2'],
    'Phase 2':['Sikanderpur','Belvedere Towers'],
    'Belvedere Towers':['Phase 2','Cyber City'],
    'Cyber City':['Belvedere Towers','Moulsari Avenue'],
    'Moulsari Avenue':['Cyber City','Phase 3']
}
